const mongoose = require('mongoose');
require('dotenv').config();
const Product = require('./models/Product');

const products = [
  { name: 'SG Abdomen Guard', brand: 'SG', category: 'abdomen-guard', price: 699, original: 867 },
  { name: 'Masuri Cricket Helmet', brand: 'Masuri', category: 'helmets', price: 3999, original: 5079 },
  { name: 'Select Brillant Ball', brand: 'Select', category: 'balls', price: 2499, original: 3499 },
  { name: 'Adidas Backpack', brand: 'Adidas', category: 'bags', price: 2999, original: 3999 },
  { name: 'Li-Ning Shuttlecocks', brand: 'Li-Ning', category: 'shuttlecocks', price: 399, original: 599 },
  { name: 'Nike Elite Basketball', brand: 'Nike', category: 'balls', price: 3499, original: 4499 },
  { name: 'Nike Kyrie 8', brand: 'Nike', category: 'shoes', price: 10999, original: 13999 },
  { name: 'LA Lakers Jersey', brand: 'Nike', category: 'jerseys', price: 6499, original: 8499 },
  { name: 'Spalding Water Bottle', brand: 'Spalding', category: 'bottles', price: 499, original: 799 },
  { name: 'Cockatoo Ab Wheel', brand: 'Cockatoo', category: 'wheels', price: 699, original: 999 },
  { name: 'Nike Running Belt', brand: 'Nike', category: 'belts', price: 899, original: 1299 },
  { name: 'SG Thigh Guard', brand: 'SG', category: 'abdomen-guard', price: 899, original: 1199 },
  { name: 'Germany Jersey 2024', brand: 'Adidas', category: 'jerseys', price: 5999, original: 7999 },
  { name: 'Nike Vapor Gloves', brand: 'Nike', category: 'gloves', price: 1999, original: 2699 },
  { name: 'Yonex Aerosensa 50', brand: 'Yonex', category: 'shuttlecocks', price: 499, original: 699 },
  { name: 'Yonex Super Grap Grip', brand: 'Yonex', category: 'grips', price: 99, original: 149 },
  { name: 'Li-Ning Net', brand: 'Li-Ning', category: 'nets', price: 4299, original: 5799 },
  { name: 'Yonex Pro Shorts', brand: 'Yonex', category: 'shorts', price: 1999, original: 2699 },
  { name: 'Wilson Evolution Ball', brand: 'Wilson', category: 'balls', price: 3999, original: 4999 },
  { name: 'NBA Wristband', brand: 'NBA', category: 'wristbands', price: 199, original: 299 },
  { name: 'BodyMax Gym Gloves', brand: 'BodyMax', category: 'gloves', price: 899, original: 1299 },
  { name: 'Adidas Running Socks', brand: 'Adidas', category: 'socks', price: 249, original: 399 },
  { name: 'Running Water Bottle', brand: 'Generic', category: 'bottles', price: 399, original: 599 },
  { name: 'Running Protein Bar', brand: 'Generic', category: 'nutrition', price: 199, original: 299 },
  { name: 'Kookaburra Cricket Bat', brand: 'Kookaburra', category: 'cricket-bats', price: 5999, original: 7999 },
  { name: 'Adidas Predator Edge', brand: 'Adidas', category: 'shoes', price: 8999, original: 11999 },
  { name: 'Puma Orbita Ball', brand: 'Puma', category: 'balls', price: 2499, original: 3499 },
  { name: 'Argentina Jersey 2024', brand: 'Adidas', category: 'jerseys', price: 5999, original: 7999 },
  { name: 'England Jersey 2024', brand: 'Nike', category: 'jerseys', price: 5999, original: 7999 },
  { name: 'Carlton Kinesis EX', brand: 'Carlton', category: 'rackets', price: 8999, original: 11999 },
  { name: 'Li-Ning Grip', brand: 'Li-Ning', category: 'grips', price: 89, original: 129 },
  { name: 'Kore 20kg Dumbbell Set', brand: 'Kore', category: 'dumbbells', price: 3999, original: 5999 },
  { name: 'BodyMax Yoga Mat', brand: 'BodyMax', category: 'mats', price: 999, original: 1499 },
  { name: 'Cockatoo Resistance Bands', brand: 'Cockatoo', category: 'bands', price: 499, original: 799 },
  { name: 'Nike Air Zoom Pegasus', brand: 'Nike', category: 'shoes', price: 8999, original: 10999 },
  { name: 'Puma Running Shorts', brand: 'Puma', category: 'shorts', price: 1799, original: 2399 },
  { name: 'SG Test Cricket Bat', brand: 'SG', category: 'cricket-bats', price: 5499, original: 6999 },
  { name: 'MRF Genius Cricket Bat', brand: 'MRF', category: 'cricket-bats', price: 7999, original: 9999 },
  { name: 'Gray-Nicolls Cricket Bat', brand: 'Gray-Nicolls', category: 'cricket-bats', price: 6499, original: 8499 },
  { name: 'CA Cricket Bat', brand: 'CA', category: 'cricket-bats', price: 6299, original: 8199 },
  { name: 'SG Cricket Ball (White)', brand: 'SG', category: 'balls', price: 899, original: 1299 },
  { name: 'Gray-Nicolls Pads', brand: 'Gray-Nicolls', category: 'batting-pads', price: 3499, original: 4499 },
  { name: 'SG Arm Guard', brand: 'SG', category: 'abdomen-guard', price: 799, original: 1099 },
  { name: 'New Balance Furon', brand: 'New Balance', category: 'shoes', price: 8299, original: 10799 },
  { name: 'Yonex BG-65 String', brand: 'Yonex', category: 'grips', price: 199, original: 299 },
  { name: 'Yonex Pro Jersey', brand: 'Yonex', category: 'jerseys', price: 3999, original: 4999 },
  { name: 'Li-Ning Badminton Jersey', brand: 'Li-Ning', category: 'jerseys', price: 3499, original: 4499 },
  { name: 'Cosco Basketball', brand: 'Cosco', category: 'balls', price: 1999, original: 2699 },
  { name: 'Golden State Jersey', brand: 'Nike', category: 'jerseys', price: 6499, original: 8499 },
  { name: 'Cosco Basketball Hoop', brand: 'Cosco', category: 'other', price: 8999, original: 11999 },
  { name: 'Cockatoo Weight Bench', brand: 'Cockatoo', category: 'benches', price: 8999, original: 11999 },
  { name: 'Kore Resistance Bands', brand: 'Kore', category: 'bands', price: 549, original: 849 },
  { name: 'Cockatoo Skipping Rope', brand: 'Cockatoo', category: 'ropes', price: 299, original: 499 },
  { name: 'Nike Dri-FIT Shorts', brand: 'Nike', category: 'shorts', price: 2499, original: 3299 },
  { name: 'Adidas Running Shorts', brand: 'Adidas', category: 'shorts', price: 2299, original: 2999 },
  { name: 'SS Ton Cricket Bat', brand: 'SS', category: 'cricket-bats', price: 5799, original: 7499 },
  { name: 'Cockatoo 20kg Dumbbell Set', brand: 'Cockatoo', category: 'dumbbells', price: 3799, original: 5499 },
  { name: 'Kore Weight Bench', brand: 'Kore', category: 'benches', price: 9499, original: 12499 },
  { name: 'Cockatoo Gym Ball', brand: 'Cockatoo', category: 'balls', price: 1299, original: 1799 },
  { name: 'Adidas Running Cap', brand: 'Adidas', category: 'caps', price: 649, original: 899 },
  { name: 'Garmin Forerunner 255', brand: 'Garmin', category: 'watches', price: 24999, original: 29999 },
  { name: 'Nike Cricket Shoes', brand: 'Nike', category: 'shoes', price: 6499, original: 7999 },
  { name: 'Under Armour Magnetico', brand: 'Under Armour', category: 'shoes', price: 8499, original: 10999 },
  { name: 'Brazil Jersey 2024', brand: 'Nike', category: 'jerseys', price: 5999, original: 7999 },
  { name: 'Nike Socks', brand: 'Nike', category: 'socks', price: 299, original: 499 },
  { name: 'Portable Goal', brand: 'Generic', category: 'goals', price: 3999, original: 5499 },
  { name: 'Yonex Power Cushion 65Z', brand: 'Yonex', category: 'shoes', price: 8999, original: 10999 },
  { name: 'Yonex BG-80 String', brand: 'Yonex', category: 'grips', price: 249, original: 349 },
  { name: 'Nike LeBron 21', brand: 'Nike', category: 'shoes', price: 12999, original: 15999 },
  { name: 'Under Armour Curry', brand: 'Under Armour', category: 'shoes', price: 11999, original: 14999 },
  { name: 'Knee Pads', brand: 'Generic', category: 'kneepads', price: 399, original: 599 },
  { name: 'Cockatoo 40kg Dumbbell Set', brand: 'Cockatoo', category: 'dumbbells', price: 5799, original: 7999 },
  { name: 'Puma Velocity Nitro', brand: 'Puma', category: 'shoes', price: 7999, original: 9999 },
  { name: 'Adidas Running Tee', brand: 'Adidas', category: 'tshirts', price: 1499, original: 1999 },
  { name: 'Kookaburra Cricket Ball', brand: 'Kookaburra', category: 'balls', price: 999, original: 1499 },
  { name: 'Spain Jersey 2024', brand: 'Adidas', category: 'jerseys', price: 5999, original: 7999 },
  { name: 'Cockatoo Treadmill', brand: 'Cockatoo', category: 'cardio', price: 29999, original: 39999 },
  { name: 'Garmin Forerunner 55', brand: 'Garmin', category: 'watches', price: 17999, original: 21999 },
  { name: 'Running Hydration Pack', brand: 'Generic', category: 'hydration', price: 2999, original: 3999 },
  { name: 'Running Energy Gel', brand: 'Generic', category: 'nutrition', price: 149, original: 249 },
  { name: 'SG Cricket Gloves', brand: 'SG', category: 'gloves', price: 1999, original: 2699 },
  { name: 'Adidas Socks', brand: 'Adidas', category: 'socks', price: 249, original: 399 },
  { name: 'Yonex Official Net', brand: 'Yonex', category: 'nets', price: 4999, original: 6499 },
  { name: 'Molten Basketball', brand: 'Molten', category: 'balls', price: 3299, original: 4299 },
  { name: 'NBA Headband', brand: 'NBA', category: 'headbands', price: 199, original: 299 },
  { name: 'BodyMax Resistance Bands', brand: 'BodyMax', category: 'bands', price: 599, original: 899 },
  { name: 'Nike Running Cap', brand: 'Nike', category: 'caps', price: 699, original: 999 },
  { name: 'Adidas Running Belt', brand: 'Adidas', category: 'belts', price: 799, original: 1199 },
  { name: 'Running Knee Brace', brand: 'Generic', category: 'braces', price: 599, original: 899 },
  { name: 'Dukes Cricket Ball', brand: 'Dukes', category: 'balls', price: 1099, original: 1599 },
  { name: 'Shrey Cricket Helmet', brand: 'Shrey', category: 'helmets', price: 2999, original: 3999 },
  { name: 'SG Cricket Pads', brand: 'SG', category: 'batting-pads', price: 2999, original: 3999 },
  { name: 'Adidas Predator Gloves', brand: 'Adidas', category: 'gloves', price: 2499, original: 3299 },
  { name: 'Yonex Aerosensa 20', brand: 'Yonex', category: 'shuttlecocks', price: 299, original: 449 },
  { name: 'Victor Badminton Shoes', brand: 'Victor', category: 'shoes', price: 7999, original: 9999 },
  { name: 'Yonex Pro Bag', brand: 'Yonex', category: 'bags', price: 3999, original: 4999 },
  { name: 'Puma Clyde All-Pro', brand: 'Puma', category: 'shoes', price: 9999, original: 12999 },
  { name: 'Chicago Bulls Jersey', brand: 'Nike', category: 'jerseys', price: 6499, original: 8499 },
  { name: 'Under Armour Shorts', brand: 'Under Armour', category: 'shorts', price: 2199, original: 2899 },
  { name: 'Basketball Pump', brand: 'Generic', category: 'pumps', price: 599, original: 899 },
  { name: 'Nike Armband', brand: 'Nike', category: 'armbands', price: 299, original: 449 },
  { name: 'BAS Cricket Bat', brand: 'BAS', category: 'cricket-bats', price: 5299, original: 6799 },
  { name: 'SG Cricket Shoes', brand: 'SG', category: 'shoes', price: 3999, original: 4999 },
  { name: 'Adidas Cricket Shoes', brand: 'Adidas', category: 'shoes', price: 5999, original: 7499 },
  { name: 'SG Cricket Kit Bag', brand: 'SG', category: 'bags', price: 4499, original: 5999 },
  { name: 'Adidas Shin Guards', brand: 'Adidas', category: 'shinguards', price: 799, original: 1199 },
  { name: 'Puma Socks', brand: 'Puma', category: 'socks', price: 229, original: 379 },
  { name: 'Yonex Astrox 100 ZZ', brand: 'Yonex', category: 'rackets', price: 15999, original: 19999 },
  { name: 'Yonex Voltric Z-Force II', brand: 'Yonex', category: 'rackets', price: 12999, original: 16999 },
  { name: 'Li-Ning Blade Pro', brand: 'Li-Ning', category: 'shoes', price: 8499, original: 10499 },
  { name: 'Victor Badminton Bag', brand: 'Victor', category: 'bags', price: 3299, original: 4299 },
  { name: 'Yonex Headband', brand: 'Yonex', category: 'headbands', price: 179, original: 269 },
  { name: 'Kore Gym Gloves', brand: 'Kore', category: 'gloves', price: 799, original: 1199 },
  { name: 'Cockatoo 12kg Kettlebell', brand: 'Cockatoo', category: 'kettlebells', price: 1799, original: 2399 },
  { name: 'Asics Gel-Nimbus 25', brand: 'Asics', category: 'shoes', price: 13999, original: 16999 },
  { name: 'New Balance Fresh Foam', brand: 'New Balance', category: 'shoes', price: 11999, original: 14999 },
  { name: 'Puma Running Tee', brand: 'Puma', category: 'tshirts', price: 1399, original: 1899 },
  { name: 'SG Cricket Ball (Red)', brand: 'SG', category: 'balls', price: 899, original: 1299 },
  { name: 'SG Cricket Helmet', brand: 'SG', category: 'helmets', price: 3499, original: 4499 },
  { name: 'Adidas Training Cones', brand: 'Adidas', category: 'cones', price: 499, original: 799 },
  { name: 'Nike Duffel Bag', brand: 'Nike', category: 'bags', price: 3499, original: 4499 },
  { name: 'Victor Net', brand: 'Victor', category: 'nets', price: 4499, original: 5999 },
  { name: 'Spalding NBA Basketball', brand: 'Spalding', category: 'balls', price: 4499, original: 5999 },
  { name: 'Nike Elite Socks', brand: 'Nike', category: 'socks', price: 299, original: 499 },
  { name: 'Nike Basketball Bag', brand: 'Nike', category: 'bags', price: 3799, original: 4799 },
  { name: 'Ankle Braces', brand: 'Generic', category: 'braces', price: 499, original: 799 },
  { name: 'Cockatoo Gym Gloves', brand: 'Cockatoo', category: 'gloves', price: 699, original: 999 },
  { name: 'Cockatoo 8kg Kettlebell', brand: 'Cockatoo', category: 'kettlebells', price: 1299, original: 1799 },
  { name: 'Cockatoo Wrist Weights', brand: 'Cockatoo', category: 'weights', price: 899, original: 1299 },
  { name: 'Nike Dri-FIT Tee', brand: 'Nike', category: 'tshirts', price: 1799, original: 2399 },
  { name: 'Nike Running Sunglasses', brand: 'Nike', category: 'sunglasses', price: 4999, original: 6999 },
  { name: 'Nike Flight Ball', brand: 'Nike', category: 'balls', price: 2799, original: 3699 },
  { name: 'Nike Shin Guards', brand: 'Nike', category: 'shinguards', price: 899, original: 1299 },
  { name: 'Spalding Basketball Hoop', brand: 'Spalding', category: 'other', price: 14999, original: 19999 },
  { name: 'Basketball Net', brand: 'Generic', category: 'nets', price: 399, original: 599 },
  { name: 'Kore 30kg Dumbbell Set', brand: 'Kore', category: 'dumbbells', price: 4999, original: 6999 },
  { name: 'BodyMax Weight Bench', brand: 'BodyMax', category: 'benches', price: 7999, original: 10999 },
  { name: 'Kore 8kg Kettlebell', brand: 'Kore', category: 'kettlebells', price: 1399, original: 1899 },
  { name: 'Running Electrolytes', brand: 'Generic', category: 'nutrition', price: 299, original: 449 },
  { name: 'SS Cricket Pads', brand: 'SS', category: 'batting-pads', price: 2799, original: 3699 },
  { name: 'SS Cricket Kit Bag', brand: 'SS', category: 'bags', price: 3999, original: 5299 },
  { name: 'SG Cricket Stumps', brand: 'SG', category: 'other', price: 1299, original: 1699 },
  { name: 'Nike Mercurial Superfly', brand: 'Nike', category: 'shoes', price: 9999, original: 12999 },
  { name: 'Puma Future Z', brand: 'Puma', category: 'shoes', price: 7999, original: 9999 },
  { name: 'Puma Ultra Gloves', brand: 'Puma', category: 'gloves', price: 1899, original: 2499 },
  { name: 'Brooklyn Nets Jersey', brand: 'Nike', category: 'jerseys', price: 6499, original: 8499 },
  { name: 'Lifetime Basketball Hoop', brand: 'Lifetime', category: 'other', price: 19999, original: 24999 },
  { name: 'Kore Yoga Mat', brand: 'Kore', category: 'mats', price: 1199, original: 1699 },
  { name: 'Cockatoo Push Up Bars', brand: 'Cockatoo', category: 'bars', price: 799, original: 1199 },
  { name: 'Adidas Ultraboost 23', brand: 'Adidas', category: 'shoes', price: 12999, original: 15999 },
  { name: 'SS Cricket Gloves', brand: 'SS', category: 'gloves', price: 1899, original: 2499 },
  { name: 'Adidas Al Rihla Ball', brand: 'Adidas', category: 'balls', price: 2999, original: 3999 },
  { name: 'Adidas Water Bottle', brand: 'Adidas', category: 'bottles', price: 599, original: 899 },
  { name: 'Li-Ning N90 III', brand: 'Li-Ning', category: 'rackets', price: 9999, original: 12999 },
  { name: 'Yonex BG-66 String', brand: 'Yonex', category: 'grips', price: 279, original: 379 },
  { name: 'Li-Ning Badminton Bag', brand: 'Li-Ning', category: 'bags', price: 3499, original: 4499 },
  { name: 'Yonex Socks', brand: 'Yonex', category: 'socks', price: 279, original: 429 },
  { name: 'Yonex Wristband', brand: 'Yonex', category: 'wristbands', price: 159, original: 249 },
  { name: 'GM Cricket Bat', brand: 'GM', category: 'cricket-bats', price: 6899, original: 8899 },
  { name: 'Gray-Nicolls Gloves', brand: 'Gray-Nicolls', category: 'gloves', price: 2299, original: 2999 },
  { name: 'Puma Shin Guards', brand: 'Puma', category: 'shinguards', price: 749, original: 1099 },
  { name: 'Victor Thruster K', brand: 'Victor', category: 'rackets', price: 10999, original: 13999 },
  { name: 'Adidas Harden Vol 7', brand: 'Adidas', category: 'shoes', price: 11999, original: 14999 },
  { name: 'Boston Celtics Jersey', brand: 'Nike', category: 'jerseys', price: 6499, original: 8499 },
  { name: 'Adidas Basketball Shorts', brand: 'Adidas', category: 'shorts', price: 2399, original: 3199 },
  { name: 'Cockatoo 30kg Dumbbell Set', brand: 'Cockatoo', category: 'dumbbells', price: 4799, original: 6799 },
  { name: 'BodyMax Barbell Set', brand: 'BodyMax', category: 'barbells', price: 6999, original: 8999 },
  { name: 'Cockatoo Ankle Weights', brand: 'Cockatoo', category: 'weights', price: 999, original: 1399 },
  { name: 'Garmin Forerunner 955', brand: 'Garmin', category: 'watches', price: 32999, original: 37999 },
  { name: 'France Jersey 2024', brand: 'Nike', category: 'jerseys', price: 5999, original: 7999 },
  { name: 'Football Rebounder', brand: 'Generic', category: 'rebounders', price: 4499, original: 5999 },
  { name: 'Yonex Aerosensa 30', brand: 'Yonex', category: 'shuttlecocks', price: 399, original: 549 },
  { name: 'Yonex Towel Grip', brand: 'Yonex', category: 'grips', price: 119, original: 169 },
  { name: 'Nike Basketball Shorts', brand: 'Nike', category: 'shorts', price: 2599, original: 3399 },
  { name: 'Kore Barbell Set', brand: 'Kore', category: 'barbells', price: 7499, original: 9499 },
  { name: 'Cockatoo Barbell Set', brand: 'Cockatoo', category: 'barbells', price: 6799, original: 8799 },
  { name: 'Cockatoo Yoga Mat', brand: 'Cockatoo', category: 'mats', price: 899, original: 1299 },
  { name: 'Nike Running Socks', brand: 'Nike', category: 'socks', price: 279, original: 429 },
  { name: 'Running Headlamp', brand: 'Generic', category: 'headlamps', price: 1299, original: 1799 },
  { name: 'Running Ankle Brace', brand: 'Generic', category: 'braces', price: 549, original: 849 }
];

async function run() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');
    
    await Product.deleteMany({});
    console.log('✅ Cleared existing products');
    
    let count = 0;
    for (const p of products) {
      await Product.create({
        name: p.name,
        brand: p.brand,
        category: p.category,
        originalPrice: p.original,
        discountedPrice: p.price,
        imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=500',
        inStock: true
      });
      count++;
      console.log(`✅ Added ${count}/${products.length}: ${p.name}`);
    }
    
    console.log(`\n🎉 SUCCESS! Added all ${count} products!`);
    console.log('🔄 Refresh your products page now!');
    process.exit();
  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

run();
